Add:tutorial_3.py
taro-kuroda-5228/future_sales_predict pull request #3
Opened 2022-02-04 14:34 UTC by taro-kuroda-5228

変更したのは以下の点です！
①予測モデルをLightGBMに変更
②ファイルを読み込むためのread_csvメソッドの作成
③pd.mergeの手順をmergeメソッドにまとめた

自分で見ても相変わらずbusyなコードで申し訳ありません💦

2022-02-05 03:24 UTC, atsushimemet requested changes
@taro-kuroda-5228 busyな箇所を0にしていく過程が、そろそろ楽しめるようになってくると思います😊修正していきましょう！

2022-02-05 03:24 UTC, atsushimemet commented on tutorial_3.py
> +mon_shop_item_cnt = sales_train[
@taro-kuroda-5228 l27とl34はmon_shop_itemとして関数にまとめられそうです。コード量を削減しましょう！

2022-02-05 03:24 UTC, atsushimemet commented on tutorial_3.py
> +def read_csv(file_name):
@taro-kuroda-5228 type hintとdocstringは必ず書きましょう！

2022-02-05 03:24 UTC, atsushimemet commented on tutorial_3.py
> +def merge(merging_df_1, merging_df_2, merged_column_lists):
@taro-kuroda-5228 type hintとdoc stringは必ず書きましょう。

2022-02-05 03:24 UTC, atsushimemet commented on tutorial_3.py
> +lag_num_list = [1,3,6,9,12]
@taro-kuroda-5228 
blackが効いてないようですが、心当たりありますか？

2022-02-05 03:24 UTC, atsushimemet commented on tutorial_3.py
> +clf = lgb.LGBMClassifier()
@taro-kuroda-5228 classifierは分類問題の際に使用します。regressorは回帰問題の際に使用します。修正してみましょう！

2022-02-05 08:00 UTC, taro-kuroda-5228 commented on tutorial_3.py
> +lag_num_list = [1,3,6,9,12]
おそらくjyupyter notebookのものをVScodeを介さなかったためだと思います！

2022-02-05 12:03 UTC, atsushimemet commented on tutorial_3.py
> +lag_num_list = [1,3,6,9,12]
@taro-kuroda-5228 了解です。[JupyterLabのおすすめ拡張機能9選](https://qiita.com/canonrock16/items/d166c93087a4aafd2db4)にjupyterへのblack導入の手引きがあるので、いれてしまいましょう！

2022-02-12 12:34 UTC, taro-kuroda-5228 commented
修正させて頂きました！

2022-02-13 02:10 UTC, atsushimemet commented
@taro-kuroda-5228 
blackによる自動整形が効いてないままだと思うのですが、Jupyter Labに自動整形の拡張機能をいれ、実行できるようにしましたか?

2022-02-14 11:54 UTC, taro-kuroda-5228 commented
すいません！ちょっとおかしくなってしまったのでこのPRも閉じますね！
そしていくらやってもjypyterのblackは働かないです、、、
よく考えたら前にもレッスン内で試みて全く働かなくて断念してました💦

2022-02-14 11:54 UTC, closed without merging